//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.directory
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : Microsoft/Telemetry/Extensions/cloud.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package Microsoft.Telemetry.Extensions;


// [Description("Describes the service related fields populated by the cloud service.")]
/**
* cloud
*/
@SuppressWarnings("all")
public class cloud extends Microsoft.Telemetry.Extension {
    // TODO: implement
    public com.microsoft.bond.BondSerializable clone() {return null;}

    //
    // Fields
    //

    // 10: Required string name
    private String name;

    // 20: Required string role
    private String role;

    // 30: Required string roleInstance
    private String roleInstance;

    // 40: Required string location
    private String location;

    // 50: Optional string roleVer
    private String roleVer;

    // 60: Optional string environment
    private String environment;

    // 70: Optional string deploymentUnit
    private String deploymentUnit;

    /**
     * @return current value of name property
     */
    public final String getName() {
        return this.name;
    }

    /**
     * @param value new value of name property
     */
    public final void setName(String value) {
        this.name = value;
    }

    /**
     * @return current value of role property
     */
    public final String getRole() {
        return this.role;
    }

    /**
     * @param value new value of role property
     */
    public final void setRole(String value) {
        this.role = value;
    }

    /**
     * @return current value of roleInstance property
     */
    public final String getRoleInstance() {
        return this.roleInstance;
    }

    /**
     * @param value new value of roleInstance property
     */
    public final void setRoleInstance(String value) {
        this.roleInstance = value;
    }

    /**
     * @return current value of location property
     */
    public final String getLocation() {
        return this.location;
    }

    /**
     * @param value new value of location property
     */
    public final void setLocation(String value) {
        this.location = value;
    }

    /**
     * @return current value of roleVer property
     */
    public final String getRoleVer() {
        return this.roleVer;
    }

    /**
     * @param value new value of roleVer property
     */
    public final void setRoleVer(String value) {
        this.roleVer = value;
    }

    /**
     * @return current value of environment property
     */
    public final String getEnvironment() {
        return this.environment;
    }

    /**
     * @param value new value of environment property
     */
    public final void setEnvironment(String value) {
        this.environment = value;
    }

    /**
     * @return current value of deploymentUnit property
     */
    public final String getDeploymentUnit() {
        return this.deploymentUnit;
    }

    /**
     * @param value new value of deploymentUnit property
     */
    public final void setDeploymentUnit(String value) {
        this.deploymentUnit = value;
    }

    /**
     * Schema metadata
     */
    public static class Schema {
        public static final com.microsoft.bond.SchemaDef schemaDef;
        public static final com.microsoft.bond.Metadata metadata;
        private static final com.microsoft.bond.Metadata name_metadata;
        private static final com.microsoft.bond.Metadata role_metadata;
        private static final com.microsoft.bond.Metadata roleInstance_metadata;
        private static final com.microsoft.bond.Metadata location_metadata;
        private static final com.microsoft.bond.Metadata roleVer_metadata;
        private static final com.microsoft.bond.Metadata environment_metadata;
        private static final com.microsoft.bond.Metadata deploymentUnit_metadata;

        static {
            metadata = new com.microsoft.bond.Metadata();
            metadata.setName("cloud");
            metadata.setQualified_name("Microsoft.Telemetry.Extensions.cloud");

            metadata.getAttributes().put("Description", "Describes the service related fields populated by the cloud service.");

            // name
            name_metadata = new com.microsoft.bond.Metadata();
            name_metadata.setName("name");
            name_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            name_metadata.getAttributes().put("Description", "Name of the service.");

            // role
            role_metadata = new com.microsoft.bond.Metadata();
            role_metadata.setName("role");
            role_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            role_metadata.getAttributes().put("Description", "Service role.");

            // roleInstance
            roleInstance_metadata = new com.microsoft.bond.Metadata();
            roleInstance_metadata.setName("roleInstance");
            roleInstance_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            roleInstance_metadata.getAttributes().put("Description", "Instance id of the deployed role instance generating the event.");

            // location
            location_metadata = new com.microsoft.bond.Metadata();
            location_metadata.setName("location");
            location_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            location_metadata.getAttributes().put("Description", "Deployed location of the role instance (canonical name of datacenter, e.g. 'East US')");

            // roleVer
            roleVer_metadata = new com.microsoft.bond.Metadata();
            roleVer_metadata.setName("roleVer");
            roleVer_metadata.getAttributes().put("Description", "Build version of the role. Recommended formats are either semantic version, or NT style: <MajorVersion>.<MinorVersion>.<Optional MileStone?>, <BuildNumber>.<Architecture>.<Branch>.<yyMMdd-hhmm>, e.g. 130.0.4590.3525.amd64fre.rd_fabric_n.140618-1229.");

            // environment
            environment_metadata = new com.microsoft.bond.Metadata();
            environment_metadata.setName("environment");
            environment_metadata.getAttributes().put("Description", "Service deployment environment or topology (e.g. Prod, PPE, ChinaProd).");

            // deploymentUnit
            deploymentUnit_metadata = new com.microsoft.bond.Metadata();
            deploymentUnit_metadata.setName("deploymentUnit");
            deploymentUnit_metadata.getAttributes().put("Description", "Service deployment or scale unit (for partitioned services).");

            schemaDef = new com.microsoft.bond.SchemaDef();
            schemaDef.setRoot(getTypeDef(schemaDef));
        }

        public static com.microsoft.bond.TypeDef getTypeDef(com.microsoft.bond.SchemaDef schema)
        {
            com.microsoft.bond.TypeDef type = new com.microsoft.bond.TypeDef();
            type.setId(com.microsoft.bond.BondDataType.BT_STRUCT);
            type.setStruct_def(getStructDef(schema));
            return type;
        }

        private static short getStructDef(com.microsoft.bond.SchemaDef schema)
        {
            short pos;

            for(pos = 0; pos < schema.getStructs().size(); pos++)
            {
                if (schema.getStructs().get(pos).getMetadata() == metadata)
                {
                    return pos;
                }
            }

            com.microsoft.bond.StructDef structDef = new com.microsoft.bond.StructDef();
            schema.getStructs().add(structDef);

            structDef.setMetadata(metadata);
            structDef.setBase_def(Microsoft.Telemetry.Extension.Schema.getTypeDef(schema));

            com.microsoft.bond.FieldDef field;

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)10);
            field.setMetadata(name_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)20);
            field.setMetadata(role_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)30);
            field.setMetadata(roleInstance_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)40);
            field.setMetadata(location_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)50);
            field.setMetadata(roleVer_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)60);
            field.setMetadata(environment_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)70);
            field.setMetadata(deploymentUnit_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            return pos;
        }
    }

    /*
    * @see com.microsoft.bond.BondMirror#getField()
    */
    public Object getField(com.microsoft.bond.FieldDef fieldDef) {
        switch (fieldDef.getId()) {
            case (short)10:
                return this.name;
            case (short)20:
                return this.role;
            case (short)30:
                return this.roleInstance;
            case (short)40:
                return this.location;
            case (short)50:
                return this.roleVer;
            case (short)60:
                return this.environment;
            case (short)70:
                return this.deploymentUnit;
            default:
                return null;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#setField()
    */
    public void setField(com.microsoft.bond.FieldDef fieldDef, Object value) {
        switch (fieldDef.getId()) {
            case (short)10:
                this.name = (String)value;
                break;
            case (short)20:
                this.role = (String)value;
                break;
            case (short)30:
                this.roleInstance = (String)value;
                break;
            case (short)40:
                this.location = (String)value;
                break;
            case (short)50:
                this.roleVer = (String)value;
                break;
            case (short)60:
                this.environment = (String)value;
                break;
            case (short)70:
                this.deploymentUnit = (String)value;
                break;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#createInstance()
    */
    public com.microsoft.bond.BondMirror createInstance(com.microsoft.bond.StructDef structDef) {
        return null;
    }

    /*
     * @see com.microsoft.bond.BondMirror#getSchema()
     */
    public com.microsoft.bond.SchemaDef getSchema()
    {
        return getRuntimeSchema();
    }

    /**
     * Static method returning {@link SchemaDef} instance.
     */
    public static com.microsoft.bond.SchemaDef getRuntimeSchema()
    {
        return Schema.schemaDef;
    }


    // Constructor
    public cloud() {
        
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("cloud", "Microsoft.Telemetry.Extensions.cloud");
    }

    protected void reset(String name, String qualifiedName) {
        super.reset(name, qualifiedName);
        this.name = "";
        this.role = "";
        this.roleInstance = "";
        this.location = "";
        this.roleVer = "";
        this.environment = "";
        this.deploymentUnit = "";
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, (com.microsoft.bond.SchemaDef)schema, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        reader.readBegin();
        readNested(reader);
        reader.readEnd();
    }

    /*
     * Called to read a struct that is contained inside another struct.
     */
    public void readNested(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        if (!reader.hasCapability(com.microsoft.bond.ProtocolCapability.TAGGED)) {
            readUntagged(reader, false);
        } else if (readTagged(reader, false)) {
            com.microsoft.bond.internal.ReadHelper.skipPartialStruct(reader);
        }
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        // read(com.microsoft.bond.internal.ProtocolHelper.createReader(reader, schema));
    }

    protected void readUntagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = reader.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);

        reader.readStructBegin(isBase);
        super.readUntagged(reader, true);

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.name = reader.readString();
        }
        else
        {
            // throw new BondException("Missing required field \"name\", id=10");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.role = reader.readString();
        }
        else
        {
            // throw new BondException("Missing required field \"role\", id=20");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.roleInstance = reader.readString();
        }
        else
        {
            // throw new BondException("Missing required field \"roleInstance\", id=30");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.location = reader.readString();
        }
        else
        {
            // throw new BondException("Missing required field \"location\", id=40");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.roleVer = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.environment = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.deploymentUnit = reader.readString();
        }
        reader.readStructEnd();
    } // ReadUntagged()


    protected boolean readTagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean isPartial;
        reader.readStructBegin(isBase);

        if (!super.readTagged(reader, true))
        {
            return false;
        }
        // BitArray seenRequiredFields = new BitArray(41);

        while (true) {
            com.microsoft.bond.ProtocolReader.FieldTag fieldTag = reader.readFieldBegin();

            if (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP
             || fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE) {
                isPartial = (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE);
                break;
            }

            switch (fieldTag.id) {
                case 10:
                    this.name = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    // seenRequiredFields.Set(10, true);
                    break;
                case 20:
                    this.role = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    // seenRequiredFields.Set(20, true);
                    break;
                case 30:
                    this.roleInstance = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    // seenRequiredFields.Set(30, true);
                    break;
                case 40:
                    this.location = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    // seenRequiredFields.Set(40, true);
                    break;
                case 50:
                    this.roleVer = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 60:
                    this.environment = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 70:
                    this.deploymentUnit = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                default:
                    reader.skip(fieldTag.type);
                    break;
            }

            reader.readFieldEnd();
        }

        reader.readStructEnd();

        //checkRequiredFieldsAreSeen(seenRequiredFields);
        return isPartial;
    }


    /*
     * @see com.microsoft.bond.BondSerializable#marshal()
     */
    public void marshal(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.marshal(this, writer);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#write()
     */
    public void write(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        writer.writeBegin();
        com.microsoft.bond.ProtocolWriter firstPassWriter;
        if ((firstPassWriter = writer.getFirstPassWriter()) != null)
        {
            writeNested(firstPassWriter, false);
            writeNested(writer, false);
        }
        else
        {
          writeNested(writer, false);
        }
        writer.writeEnd();
    }

    public void writeNested(com.microsoft.bond.ProtocolWriter writer, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = writer.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);
        writer.writeStructBegin(Schema.metadata, isBase);
        super.writeNested(writer, true);

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.name_metadata);
        writer.writeString(name);
        writer.writeFieldEnd();

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 20, Schema.role_metadata);
        writer.writeString(role);
        writer.writeFieldEnd();

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 30, Schema.roleInstance_metadata);
        writer.writeString(roleInstance);
        writer.writeFieldEnd();

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 40, Schema.location_metadata);
        writer.writeString(location);
        writer.writeFieldEnd();

        if (!canOmitFields || (roleVer != Schema.roleVer_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 50, Schema.roleVer_metadata);
            writer.writeString(roleVer);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 50, Schema.roleVer_metadata);
        }

        if (!canOmitFields || (environment != Schema.environment_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 60, Schema.environment_metadata);
            writer.writeString(environment);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 60, Schema.environment_metadata);
        }

        if (!canOmitFields || (deploymentUnit != Schema.deploymentUnit_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 70, Schema.deploymentUnit_metadata);
            writer.writeString(deploymentUnit);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 70, Schema.deploymentUnit_metadata);
        }

        writer.writeStructEnd(isBase);
    } // writeNested


    public boolean memberwiseCompare(Object obj) {
        if (obj == null) {
            return false;
        }

        cloud that = (cloud)obj;

        return memberwiseCompareQuick(that) && memberwiseCompareDeep(that);
    }

    protected boolean memberwiseCompareQuick(cloud that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareQuick(that);
        equals = equals && ((this.name == null) == (that.name == null));
        equals = equals && (this.name == null ? true : (this.name.length() == that.name.length()));
        equals = equals && ((this.role == null) == (that.role == null));
        equals = equals && (this.role == null ? true : (this.role.length() == that.role.length()));
        equals = equals && ((this.roleInstance == null) == (that.roleInstance == null));
        equals = equals && (this.roleInstance == null ? true : (this.roleInstance.length() == that.roleInstance.length()));
        equals = equals && ((this.location == null) == (that.location == null));
        equals = equals && (this.location == null ? true : (this.location.length() == that.location.length()));
        equals = equals && ((this.roleVer == null) == (that.roleVer == null));
        equals = equals && (this.roleVer == null ? true : (this.roleVer.length() == that.roleVer.length()));
        equals = equals && ((this.environment == null) == (that.environment == null));
        equals = equals && (this.environment == null ? true : (this.environment.length() == that.environment.length()));
        equals = equals && ((this.deploymentUnit == null) == (that.deploymentUnit == null));
        equals = equals && (this.deploymentUnit == null ? true : (this.deploymentUnit.length() == that.deploymentUnit.length()));
        return equals;
    } // memberwiseCompareQuick

    protected boolean memberwiseCompareDeep(cloud that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareDeep(that);
        equals = equals && (this.name == null ? true : this.name.equals(that.name));
        equals = equals && (this.role == null ? true : this.role.equals(that.role));
        equals = equals && (this.roleInstance == null ? true : this.roleInstance.equals(that.roleInstance));
        equals = equals && (this.location == null ? true : this.location.equals(that.location));
        equals = equals && (this.roleVer == null ? true : this.roleVer.equals(that.roleVer));
        equals = equals && (this.environment == null ? true : this.environment.equals(that.environment));
        equals = equals && (this.deploymentUnit == null ? true : this.deploymentUnit.equals(that.deploymentUnit));
        return equals;
    } // memberwiseCompareDeep

}; // class cloud
