//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.directory
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : Microsoft/Telemetry/Extensions/sll.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package Microsoft.Telemetry.Extensions;


// [Description("Describes the fields related to a service logging library implementation.")]
/**
* sll
*/
@SuppressWarnings("all")
public class sll extends Microsoft.Telemetry.Extension {
    // TODO: implement
    public com.microsoft.bond.BondSerializable clone() {return null;}

    //
    // Fields
    //

    // 10: Optional string libVer
    private String libVer;

    // 20: Required Microsoft.Telemetry.Extensions.TracingEventLevel level
    private Microsoft.Telemetry.Extensions.TracingEventLevel level;

    /**
     * @return current value of libVer property
     */
    public final String getLibVer() {
        return this.libVer;
    }

    /**
     * @param value new value of libVer property
     */
    public final void setLibVer(String value) {
        this.libVer = value;
    }

    /**
     * @return current value of level property
     */
    public final Microsoft.Telemetry.Extensions.TracingEventLevel getLevel() {
        return this.level;
    }

    /**
     * @param value new value of level property
     */
    public final void setLevel(Microsoft.Telemetry.Extensions.TracingEventLevel value) {
        this.level = value;
    }

    /**
     * Schema metadata
     */
    public static class Schema {
        public static final com.microsoft.bond.SchemaDef schemaDef;
        public static final com.microsoft.bond.Metadata metadata;
        private static final com.microsoft.bond.Metadata libVer_metadata;
        private static final com.microsoft.bond.Metadata level_metadata;

        static {
            metadata = new com.microsoft.bond.Metadata();
            metadata.setName("sll");
            metadata.setQualified_name("Microsoft.Telemetry.Extensions.sll");

            metadata.getAttributes().put("Description", "Describes the fields related to a service logging library implementation.");

            // libVer
            libVer_metadata = new com.microsoft.bond.Metadata();
            libVer_metadata.setName("libVer");
            libVer_metadata.getAttributes().put("Description", "Service Logging Library version");

            // level
            level_metadata = new com.microsoft.bond.Metadata();
            level_metadata.setName("level");
            level_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            level_metadata.getAttributes().put("Description", "Severity level for service event");
            level_metadata.getDefault_value().setInt_value(Microsoft.Telemetry.Extensions.TracingEventLevel.None.getValue());

            schemaDef = new com.microsoft.bond.SchemaDef();
            schemaDef.setRoot(getTypeDef(schemaDef));
        }

        public static com.microsoft.bond.TypeDef getTypeDef(com.microsoft.bond.SchemaDef schema)
        {
            com.microsoft.bond.TypeDef type = new com.microsoft.bond.TypeDef();
            type.setId(com.microsoft.bond.BondDataType.BT_STRUCT);
            type.setStruct_def(getStructDef(schema));
            return type;
        }

        private static short getStructDef(com.microsoft.bond.SchemaDef schema)
        {
            short pos;

            for(pos = 0; pos < schema.getStructs().size(); pos++)
            {
                if (schema.getStructs().get(pos).getMetadata() == metadata)
                {
                    return pos;
                }
            }

            com.microsoft.bond.StructDef structDef = new com.microsoft.bond.StructDef();
            schema.getStructs().add(structDef);

            structDef.setMetadata(metadata);
            structDef.setBase_def(Microsoft.Telemetry.Extension.Schema.getTypeDef(schema));

            com.microsoft.bond.FieldDef field;

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)10);
            field.setMetadata(libVer_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)20);
            field.setMetadata(level_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_INT32);
            structDef.getFields().add(field);

            return pos;
        }
    }

    /*
    * @see com.microsoft.bond.BondMirror#getField()
    */
    public Object getField(com.microsoft.bond.FieldDef fieldDef) {
        switch (fieldDef.getId()) {
            case (short)10:
                return this.libVer;
            case (short)20:
                return this.level;
            default:
                return null;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#setField()
    */
    public void setField(com.microsoft.bond.FieldDef fieldDef, Object value) {
        switch (fieldDef.getId()) {
            case (short)10:
                this.libVer = (String)value;
                break;
            case (short)20:
                this.level = (Microsoft.Telemetry.Extensions.TracingEventLevel)value;
                break;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#createInstance()
    */
    public com.microsoft.bond.BondMirror createInstance(com.microsoft.bond.StructDef structDef) {
        return null;
    }

    /*
     * @see com.microsoft.bond.BondMirror#getSchema()
     */
    public com.microsoft.bond.SchemaDef getSchema()
    {
        return getRuntimeSchema();
    }

    /**
     * Static method returning {@link SchemaDef} instance.
     */
    public static com.microsoft.bond.SchemaDef getRuntimeSchema()
    {
        return Schema.schemaDef;
    }


    // Constructor
    public sll() {
        
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("sll", "Microsoft.Telemetry.Extensions.sll");
    }

    protected void reset(String name, String qualifiedName) {
        super.reset(name, qualifiedName);
        this.libVer = "";
        this.level = Microsoft.Telemetry.Extensions.TracingEventLevel.None;
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, (com.microsoft.bond.SchemaDef)schema, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        reader.readBegin();
        readNested(reader);
        reader.readEnd();
    }

    /*
     * Called to read a struct that is contained inside another struct.
     */
    public void readNested(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        if (!reader.hasCapability(com.microsoft.bond.ProtocolCapability.TAGGED)) {
            readUntagged(reader, false);
        } else if (readTagged(reader, false)) {
            com.microsoft.bond.internal.ReadHelper.skipPartialStruct(reader);
        }
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        // read(com.microsoft.bond.internal.ProtocolHelper.createReader(reader, schema));
    }

    protected void readUntagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = reader.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);

        reader.readStructBegin(isBase);
        super.readUntagged(reader, true);

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.libVer = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.level = Microsoft.Telemetry.Extensions.TracingEventLevel.fromValue(reader.readInt32());
        }
        else
        {
            // throw new BondException("Missing required field \"level\", id=20");
        }
        reader.readStructEnd();
    } // ReadUntagged()


    protected boolean readTagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean isPartial;
        reader.readStructBegin(isBase);

        if (!super.readTagged(reader, true))
        {
            return false;
        }
        // BitArray seenRequiredFields = new BitArray(21);

        while (true) {
            com.microsoft.bond.ProtocolReader.FieldTag fieldTag = reader.readFieldBegin();

            if (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP
             || fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE) {
                isPartial = (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE);
                break;
            }

            switch (fieldTag.id) {
                case 10:
                    this.libVer = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 20:
                    this.level = Microsoft.Telemetry.Extensions.TracingEventLevel.fromValue(com.microsoft.bond.internal.ReadHelper.readInt32(reader, fieldTag.type));
                    // seenRequiredFields.Set(20, true);
                    break;
                default:
                    reader.skip(fieldTag.type);
                    break;
            }

            reader.readFieldEnd();
        }

        reader.readStructEnd();

        //checkRequiredFieldsAreSeen(seenRequiredFields);
        return isPartial;
    }


    /*
     * @see com.microsoft.bond.BondSerializable#marshal()
     */
    public void marshal(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.marshal(this, writer);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#write()
     */
    public void write(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        writer.writeBegin();
        com.microsoft.bond.ProtocolWriter firstPassWriter;
        if ((firstPassWriter = writer.getFirstPassWriter()) != null)
        {
            writeNested(firstPassWriter, false);
            writeNested(writer, false);
        }
        else
        {
          writeNested(writer, false);
        }
        writer.writeEnd();
    }

    public void writeNested(com.microsoft.bond.ProtocolWriter writer, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = writer.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);
        writer.writeStructBegin(Schema.metadata, isBase);
        super.writeNested(writer, true);

        if (!canOmitFields || (libVer != Schema.libVer_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.libVer_metadata);
            writer.writeString(libVer);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.libVer_metadata);
        }

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_INT32, 20, Schema.level_metadata);
        writer.writeInt32(level.getValue());
        writer.writeFieldEnd();

        writer.writeStructEnd(isBase);
    } // writeNested


    public boolean memberwiseCompare(Object obj) {
        if (obj == null) {
            return false;
        }

        sll that = (sll)obj;

        return memberwiseCompareQuick(that) && memberwiseCompareDeep(that);
    }

    protected boolean memberwiseCompareQuick(sll that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareQuick(that);
        equals = equals && ((this.libVer == null) == (that.libVer == null));
        equals = equals && (this.libVer == null ? true : (this.libVer.length() == that.libVer.length()));
        equals = equals && (this.level == that.level);
        return equals;
    } // memberwiseCompareQuick

    protected boolean memberwiseCompareDeep(sll that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareDeep(that);
        equals = equals && (this.libVer == null ? true : this.libVer.equals(that.libVer));
        return equals;
    } // memberwiseCompareDeep

}; // class sll
