//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.directory
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : Microsoft/Telemetry/Extensions/TracingEventLevel.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package Microsoft.Telemetry.Extensions;


// [Description("Standard tracing event level. See also System.Diagnostics.Tracing.EventLevel.")]
/**
* TracingEventLevel
*/
public enum TracingEventLevel {
    None(0),
    Critical(1),
    Error(2),
    Informational(3),
    LogAlways(4),
    Verbose(5),
    Warning(6),
    __INVALID_ENUM_VALUE(7);

    private final int value;

    TracingEventLevel(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static TracingEventLevel fromValue(int value) {
        switch (value) {
            case 0:
                return None;
            case 1:
                return Critical;
            case 2:
                return Error;
            case 3:
                return Informational;
            case 4:
                return LogAlways;
            case 5:
                return Verbose;
            case 6:
                return Warning;
        }
        return __INVALID_ENUM_VALUE;
    }
}; // enum TracingEventLevel

