//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.directory
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : Microsoft/Telemetry/Extensions/xbox.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package Microsoft.Telemetry.Extensions;


// [Description("Describes the XBox related fields and might be populated by the console.")]
/**
* xbox
*/
@SuppressWarnings("all")
public class xbox extends Microsoft.Telemetry.Extension {
    // TODO: implement
    public com.microsoft.bond.BondSerializable clone() {return null;}

    //
    // Fields
    //

    // 10: Optional string sti
    private String sti;

    // 20: Optional string eventSequence
    private String eventSequence;

    // 30: Optional string issueTimestamp
    private String issueTimestamp;

    // 40: Optional string expiryTimestamp
    private String expiryTimestamp;

    // 50: Optional string sandboxId
    private String sandboxId;

    // 60: Optional string deviceType
    private String deviceType;

    // 70: Optional string xblDeviceId
    private String xblDeviceId;

    // 80: Optional string signedInUsers
    private String signedInUsers;

    // 90: Optional string isDevelopmentAccount
    private String isDevelopmentAccount;

    // 100: Optional string isTestAccount
    private String isTestAccount;

    // 110: Optional string titleId
    private String titleId;

    /**
     * @return current value of sti property
     */
    public final String getSti() {
        return this.sti;
    }

    /**
     * @param value new value of sti property
     */
    public final void setSti(String value) {
        this.sti = value;
    }

    /**
     * @return current value of eventSequence property
     */
    public final String getEventSequence() {
        return this.eventSequence;
    }

    /**
     * @param value new value of eventSequence property
     */
    public final void setEventSequence(String value) {
        this.eventSequence = value;
    }

    /**
     * @return current value of issueTimestamp property
     */
    public final String getIssueTimestamp() {
        return this.issueTimestamp;
    }

    /**
     * @param value new value of issueTimestamp property
     */
    public final void setIssueTimestamp(String value) {
        this.issueTimestamp = value;
    }

    /**
     * @return current value of expiryTimestamp property
     */
    public final String getExpiryTimestamp() {
        return this.expiryTimestamp;
    }

    /**
     * @param value new value of expiryTimestamp property
     */
    public final void setExpiryTimestamp(String value) {
        this.expiryTimestamp = value;
    }

    /**
     * @return current value of sandboxId property
     */
    public final String getSandboxId() {
        return this.sandboxId;
    }

    /**
     * @param value new value of sandboxId property
     */
    public final void setSandboxId(String value) {
        this.sandboxId = value;
    }

    /**
     * @return current value of deviceType property
     */
    public final String getDeviceType() {
        return this.deviceType;
    }

    /**
     * @param value new value of deviceType property
     */
    public final void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * @return current value of xblDeviceId property
     */
    public final String getXblDeviceId() {
        return this.xblDeviceId;
    }

    /**
     * @param value new value of xblDeviceId property
     */
    public final void setXblDeviceId(String value) {
        this.xblDeviceId = value;
    }

    /**
     * @return current value of signedInUsers property
     */
    public final String getSignedInUsers() {
        return this.signedInUsers;
    }

    /**
     * @param value new value of signedInUsers property
     */
    public final void setSignedInUsers(String value) {
        this.signedInUsers = value;
    }

    /**
     * @return current value of isDevelopmentAccount property
     */
    public final String getIsDevelopmentAccount() {
        return this.isDevelopmentAccount;
    }

    /**
     * @param value new value of isDevelopmentAccount property
     */
    public final void setIsDevelopmentAccount(String value) {
        this.isDevelopmentAccount = value;
    }

    /**
     * @return current value of isTestAccount property
     */
    public final String getIsTestAccount() {
        return this.isTestAccount;
    }

    /**
     * @param value new value of isTestAccount property
     */
    public final void setIsTestAccount(String value) {
        this.isTestAccount = value;
    }

    /**
     * @return current value of titleId property
     */
    public final String getTitleId() {
        return this.titleId;
    }

    /**
     * @param value new value of titleId property
     */
    public final void setTitleId(String value) {
        this.titleId = value;
    }

    /**
     * Schema metadata
     */
    public static class Schema {
        public static final com.microsoft.bond.SchemaDef schemaDef;
        public static final com.microsoft.bond.Metadata metadata;
        private static final com.microsoft.bond.Metadata sti_metadata;
        private static final com.microsoft.bond.Metadata eventSequence_metadata;
        private static final com.microsoft.bond.Metadata issueTimestamp_metadata;
        private static final com.microsoft.bond.Metadata expiryTimestamp_metadata;
        private static final com.microsoft.bond.Metadata sandboxId_metadata;
        private static final com.microsoft.bond.Metadata deviceType_metadata;
        private static final com.microsoft.bond.Metadata xblDeviceId_metadata;
        private static final com.microsoft.bond.Metadata signedInUsers_metadata;
        private static final com.microsoft.bond.Metadata isDevelopmentAccount_metadata;
        private static final com.microsoft.bond.Metadata isTestAccount_metadata;
        private static final com.microsoft.bond.Metadata titleId_metadata;

        static {
            metadata = new com.microsoft.bond.Metadata();
            metadata.setName("xbox");
            metadata.setQualified_name("Microsoft.Telemetry.Extensions.xbox");

            metadata.getAttributes().put("Description", "Describes the XBox related fields and might be populated by the console.");

            // sti
            sti_metadata = new com.microsoft.bond.Metadata();
            sti_metadata.setName("sti");
            sti_metadata.getAttributes().put("Description", "XBox supporting token index.");

            // eventSequence
            eventSequence_metadata = new com.microsoft.bond.Metadata();
            eventSequence_metadata.setName("eventSequence");
            eventSequence_metadata.getAttributes().put("Description", "XBox event sequence.");

            // issueTimestamp
            issueTimestamp_metadata = new com.microsoft.bond.Metadata();
            issueTimestamp_metadata.setName("issueTimestamp");
            issueTimestamp_metadata.getAttributes().put("Description", "Xbox token issue timestamp.");

            // expiryTimestamp
            expiryTimestamp_metadata = new com.microsoft.bond.Metadata();
            expiryTimestamp_metadata.setName("expiryTimestamp");
            expiryTimestamp_metadata.getAttributes().put("Description", "XBox token expiry timestamp.");

            // sandboxId
            sandboxId_metadata = new com.microsoft.bond.Metadata();
            sandboxId_metadata.setName("sandboxId");
            sandboxId_metadata.getAttributes().put("Description", "Xbox sandboxId.");

            // deviceType
            deviceType_metadata = new com.microsoft.bond.Metadata();
            deviceType_metadata.setName("deviceType");
            deviceType_metadata.getAttributes().put("Description", "XBox device type.");

            // xblDeviceId
            xblDeviceId_metadata = new com.microsoft.bond.Metadata();
            xblDeviceId_metadata.setName("xblDeviceId");
            xblDeviceId_metadata.getAttributes().put("Description", "Xbox live deviceId.");

            // signedInUsers
            signedInUsers_metadata = new com.microsoft.bond.Metadata();
            signedInUsers_metadata.setName("signedInUsers");
            signedInUsers_metadata.getAttributes().put("Description", "XBox signed in Xuids.");

            // isDevelopmentAccount
            isDevelopmentAccount_metadata = new com.microsoft.bond.Metadata();
            isDevelopmentAccount_metadata.setName("isDevelopmentAccount");
            isDevelopmentAccount_metadata.getAttributes().put("Description", "XBox is development account.");

            // isTestAccount
            isTestAccount_metadata = new com.microsoft.bond.Metadata();
            isTestAccount_metadata.setName("isTestAccount");
            isTestAccount_metadata.getAttributes().put("Description", "XBox is test account.");

            // titleId
            titleId_metadata = new com.microsoft.bond.Metadata();
            titleId_metadata.setName("titleId");
            titleId_metadata.getAttributes().put("Description", "XBox titleId.");

            schemaDef = new com.microsoft.bond.SchemaDef();
            schemaDef.setRoot(getTypeDef(schemaDef));
        }

        public static com.microsoft.bond.TypeDef getTypeDef(com.microsoft.bond.SchemaDef schema)
        {
            com.microsoft.bond.TypeDef type = new com.microsoft.bond.TypeDef();
            type.setId(com.microsoft.bond.BondDataType.BT_STRUCT);
            type.setStruct_def(getStructDef(schema));
            return type;
        }

        private static short getStructDef(com.microsoft.bond.SchemaDef schema)
        {
            short pos;

            for(pos = 0; pos < schema.getStructs().size(); pos++)
            {
                if (schema.getStructs().get(pos).getMetadata() == metadata)
                {
                    return pos;
                }
            }

            com.microsoft.bond.StructDef structDef = new com.microsoft.bond.StructDef();
            schema.getStructs().add(structDef);

            structDef.setMetadata(metadata);
            structDef.setBase_def(Microsoft.Telemetry.Extension.Schema.getTypeDef(schema));

            com.microsoft.bond.FieldDef field;

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)10);
            field.setMetadata(sti_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)20);
            field.setMetadata(eventSequence_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)30);
            field.setMetadata(issueTimestamp_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)40);
            field.setMetadata(expiryTimestamp_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)50);
            field.setMetadata(sandboxId_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)60);
            field.setMetadata(deviceType_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)70);
            field.setMetadata(xblDeviceId_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)80);
            field.setMetadata(signedInUsers_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)90);
            field.setMetadata(isDevelopmentAccount_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)100);
            field.setMetadata(isTestAccount_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)110);
            field.setMetadata(titleId_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            return pos;
        }
    }

    /*
    * @see com.microsoft.bond.BondMirror#getField()
    */
    public Object getField(com.microsoft.bond.FieldDef fieldDef) {
        switch (fieldDef.getId()) {
            case (short)10:
                return this.sti;
            case (short)20:
                return this.eventSequence;
            case (short)30:
                return this.issueTimestamp;
            case (short)40:
                return this.expiryTimestamp;
            case (short)50:
                return this.sandboxId;
            case (short)60:
                return this.deviceType;
            case (short)70:
                return this.xblDeviceId;
            case (short)80:
                return this.signedInUsers;
            case (short)90:
                return this.isDevelopmentAccount;
            case (short)100:
                return this.isTestAccount;
            case (short)110:
                return this.titleId;
            default:
                return null;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#setField()
    */
    public void setField(com.microsoft.bond.FieldDef fieldDef, Object value) {
        switch (fieldDef.getId()) {
            case (short)10:
                this.sti = (String)value;
                break;
            case (short)20:
                this.eventSequence = (String)value;
                break;
            case (short)30:
                this.issueTimestamp = (String)value;
                break;
            case (short)40:
                this.expiryTimestamp = (String)value;
                break;
            case (short)50:
                this.sandboxId = (String)value;
                break;
            case (short)60:
                this.deviceType = (String)value;
                break;
            case (short)70:
                this.xblDeviceId = (String)value;
                break;
            case (short)80:
                this.signedInUsers = (String)value;
                break;
            case (short)90:
                this.isDevelopmentAccount = (String)value;
                break;
            case (short)100:
                this.isTestAccount = (String)value;
                break;
            case (short)110:
                this.titleId = (String)value;
                break;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#createInstance()
    */
    public com.microsoft.bond.BondMirror createInstance(com.microsoft.bond.StructDef structDef) {
        return null;
    }

    /*
     * @see com.microsoft.bond.BondMirror#getSchema()
     */
    public com.microsoft.bond.SchemaDef getSchema()
    {
        return getRuntimeSchema();
    }

    /**
     * Static method returning {@link SchemaDef} instance.
     */
    public static com.microsoft.bond.SchemaDef getRuntimeSchema()
    {
        return Schema.schemaDef;
    }


    // Constructor
    public xbox() {
        
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("xbox", "Microsoft.Telemetry.Extensions.xbox");
    }

    protected void reset(String name, String qualifiedName) {
        super.reset(name, qualifiedName);
        this.sti = "";
        this.eventSequence = "";
        this.issueTimestamp = "";
        this.expiryTimestamp = "";
        this.sandboxId = "";
        this.deviceType = "";
        this.xblDeviceId = "";
        this.signedInUsers = "";
        this.isDevelopmentAccount = "";
        this.isTestAccount = "";
        this.titleId = "";
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, (com.microsoft.bond.SchemaDef)schema, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        reader.readBegin();
        readNested(reader);
        reader.readEnd();
    }

    /*
     * Called to read a struct that is contained inside another struct.
     */
    public void readNested(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        if (!reader.hasCapability(com.microsoft.bond.ProtocolCapability.TAGGED)) {
            readUntagged(reader, false);
        } else if (readTagged(reader, false)) {
            com.microsoft.bond.internal.ReadHelper.skipPartialStruct(reader);
        }
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        // read(com.microsoft.bond.internal.ProtocolHelper.createReader(reader, schema));
    }

    protected void readUntagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = reader.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);

        reader.readStructBegin(isBase);
        super.readUntagged(reader, true);

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.sti = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.eventSequence = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.issueTimestamp = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.expiryTimestamp = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.sandboxId = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.deviceType = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.xblDeviceId = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.signedInUsers = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.isDevelopmentAccount = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.isTestAccount = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.titleId = reader.readString();
        }
        reader.readStructEnd();
    } // ReadUntagged()


    protected boolean readTagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean isPartial;
        reader.readStructBegin(isBase);

        if (!super.readTagged(reader, true))
        {
            return false;
        }

        while (true) {
            com.microsoft.bond.ProtocolReader.FieldTag fieldTag = reader.readFieldBegin();

            if (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP
             || fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE) {
                isPartial = (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE);
                break;
            }

            switch (fieldTag.id) {
                case 10:
                    this.sti = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 20:
                    this.eventSequence = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 30:
                    this.issueTimestamp = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 40:
                    this.expiryTimestamp = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 50:
                    this.sandboxId = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 60:
                    this.deviceType = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 70:
                    this.xblDeviceId = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 80:
                    this.signedInUsers = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 90:
                    this.isDevelopmentAccount = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 100:
                    this.isTestAccount = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 110:
                    this.titleId = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                default:
                    reader.skip(fieldTag.type);
                    break;
            }

            reader.readFieldEnd();
        }

        reader.readStructEnd();

        return isPartial;
    }


    /*
     * @see com.microsoft.bond.BondSerializable#marshal()
     */
    public void marshal(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.marshal(this, writer);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#write()
     */
    public void write(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        writer.writeBegin();
        com.microsoft.bond.ProtocolWriter firstPassWriter;
        if ((firstPassWriter = writer.getFirstPassWriter()) != null)
        {
            writeNested(firstPassWriter, false);
            writeNested(writer, false);
        }
        else
        {
          writeNested(writer, false);
        }
        writer.writeEnd();
    }

    public void writeNested(com.microsoft.bond.ProtocolWriter writer, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = writer.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);
        writer.writeStructBegin(Schema.metadata, isBase);
        super.writeNested(writer, true);

        if (!canOmitFields || (sti != Schema.sti_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.sti_metadata);
            writer.writeString(sti);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.sti_metadata);
        }

        if (!canOmitFields || (eventSequence != Schema.eventSequence_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 20, Schema.eventSequence_metadata);
            writer.writeString(eventSequence);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 20, Schema.eventSequence_metadata);
        }

        if (!canOmitFields || (issueTimestamp != Schema.issueTimestamp_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 30, Schema.issueTimestamp_metadata);
            writer.writeString(issueTimestamp);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 30, Schema.issueTimestamp_metadata);
        }

        if (!canOmitFields || (expiryTimestamp != Schema.expiryTimestamp_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 40, Schema.expiryTimestamp_metadata);
            writer.writeString(expiryTimestamp);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 40, Schema.expiryTimestamp_metadata);
        }

        if (!canOmitFields || (sandboxId != Schema.sandboxId_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 50, Schema.sandboxId_metadata);
            writer.writeString(sandboxId);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 50, Schema.sandboxId_metadata);
        }

        if (!canOmitFields || (deviceType != Schema.deviceType_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 60, Schema.deviceType_metadata);
            writer.writeString(deviceType);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 60, Schema.deviceType_metadata);
        }

        if (!canOmitFields || (xblDeviceId != Schema.xblDeviceId_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 70, Schema.xblDeviceId_metadata);
            writer.writeString(xblDeviceId);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 70, Schema.xblDeviceId_metadata);
        }

        if (!canOmitFields || (signedInUsers != Schema.signedInUsers_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 80, Schema.signedInUsers_metadata);
            writer.writeString(signedInUsers);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 80, Schema.signedInUsers_metadata);
        }

        if (!canOmitFields || (isDevelopmentAccount != Schema.isDevelopmentAccount_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 90, Schema.isDevelopmentAccount_metadata);
            writer.writeString(isDevelopmentAccount);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 90, Schema.isDevelopmentAccount_metadata);
        }

        if (!canOmitFields || (isTestAccount != Schema.isTestAccount_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 100, Schema.isTestAccount_metadata);
            writer.writeString(isTestAccount);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 100, Schema.isTestAccount_metadata);
        }

        if (!canOmitFields || (titleId != Schema.titleId_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 110, Schema.titleId_metadata);
            writer.writeString(titleId);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 110, Schema.titleId_metadata);
        }

        writer.writeStructEnd(isBase);
    } // writeNested


    public boolean memberwiseCompare(Object obj) {
        if (obj == null) {
            return false;
        }

        xbox that = (xbox)obj;

        return memberwiseCompareQuick(that) && memberwiseCompareDeep(that);
    }

    protected boolean memberwiseCompareQuick(xbox that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareQuick(that);
        equals = equals && ((this.sti == null) == (that.sti == null));
        equals = equals && (this.sti == null ? true : (this.sti.length() == that.sti.length()));
        equals = equals && ((this.eventSequence == null) == (that.eventSequence == null));
        equals = equals && (this.eventSequence == null ? true : (this.eventSequence.length() == that.eventSequence.length()));
        equals = equals && ((this.issueTimestamp == null) == (that.issueTimestamp == null));
        equals = equals && (this.issueTimestamp == null ? true : (this.issueTimestamp.length() == that.issueTimestamp.length()));
        equals = equals && ((this.expiryTimestamp == null) == (that.expiryTimestamp == null));
        equals = equals && (this.expiryTimestamp == null ? true : (this.expiryTimestamp.length() == that.expiryTimestamp.length()));
        equals = equals && ((this.sandboxId == null) == (that.sandboxId == null));
        equals = equals && (this.sandboxId == null ? true : (this.sandboxId.length() == that.sandboxId.length()));
        equals = equals && ((this.deviceType == null) == (that.deviceType == null));
        equals = equals && (this.deviceType == null ? true : (this.deviceType.length() == that.deviceType.length()));
        equals = equals && ((this.xblDeviceId == null) == (that.xblDeviceId == null));
        equals = equals && (this.xblDeviceId == null ? true : (this.xblDeviceId.length() == that.xblDeviceId.length()));
        equals = equals && ((this.signedInUsers == null) == (that.signedInUsers == null));
        equals = equals && (this.signedInUsers == null ? true : (this.signedInUsers.length() == that.signedInUsers.length()));
        equals = equals && ((this.isDevelopmentAccount == null) == (that.isDevelopmentAccount == null));
        equals = equals && (this.isDevelopmentAccount == null ? true : (this.isDevelopmentAccount.length() == that.isDevelopmentAccount.length()));
        equals = equals && ((this.isTestAccount == null) == (that.isTestAccount == null));
        equals = equals && (this.isTestAccount == null ? true : (this.isTestAccount.length() == that.isTestAccount.length()));
        equals = equals && ((this.titleId == null) == (that.titleId == null));
        equals = equals && (this.titleId == null ? true : (this.titleId.length() == that.titleId.length()));
        return equals;
    } // memberwiseCompareQuick

    protected boolean memberwiseCompareDeep(xbox that) {
        boolean equals = true;
        equals = equals && super.memberwiseCompareDeep(that);
        equals = equals && (this.sti == null ? true : this.sti.equals(that.sti));
        equals = equals && (this.eventSequence == null ? true : this.eventSequence.equals(that.eventSequence));
        equals = equals && (this.issueTimestamp == null ? true : this.issueTimestamp.equals(that.issueTimestamp));
        equals = equals && (this.expiryTimestamp == null ? true : this.expiryTimestamp.equals(that.expiryTimestamp));
        equals = equals && (this.sandboxId == null ? true : this.sandboxId.equals(that.sandboxId));
        equals = equals && (this.deviceType == null ? true : this.deviceType.equals(that.deviceType));
        equals = equals && (this.xblDeviceId == null ? true : this.xblDeviceId.equals(that.xblDeviceId));
        equals = equals && (this.signedInUsers == null ? true : this.signedInUsers.equals(that.signedInUsers));
        equals = equals && (this.isDevelopmentAccount == null ? true : this.isDevelopmentAccount.equals(that.isDevelopmentAccount));
        equals = equals && (this.isTestAccount == null ? true : this.isTestAccount.equals(that.isTestAccount));
        equals = equals && (this.titleId == null ? true : this.titleId.equals(that.titleId));
        return equals;
    } // memberwiseCompareDeep

}; // class xbox
